export const TOUR_STORAGE_KEY = 'tienlen_tour_v1_done'

export const TOUR_STEPS = [
  {
    id: 'player-name',
    target: '[data-tour="player-name"]',
    title: 'Nhập tên người chơi',
    content: 'Gõ tên vào ô này — ví dụ: An, Bình, Chi…',
    tab: 'players',
    requireAction: true,
    waiting: 'Hãy nhập ít nhất 1 ký tự vào ô tên.',
  },
  {
    id: 'player-add',
    target: '[data-tour="player-add"]',
    title: 'Thêm người chơi',
    content: 'Bấm nút + Thêm để lưu người chơi vào danh sách.',
    tab: 'players',
    requireAction: true,
    waiting: 'Bấm + Thêm để thêm người chơi.',
  },
  {
    id: 'player-select',
    target: '[data-tour="player-select"]',
    title: 'Chọn người ở bàn',
    content: 'Tick chọn từ 2 đến 4 người sẽ ngồi chơi ván này.',
    tab: 'players',
    requireAction: true,
    waiting: 'Chọn ít nhất 2 người chơi.',
  },
  {
    id: 'start-session',
    target: '[data-tour="start-session"]',
    title: 'Bắt đầu phiên',
    content: 'Bấm để mở phiên chơi mới với những người đã chọn.',
    tab: 'players',
    requireAction: true,
    waiting: 'Bấm Bắt đầu phiên.',
  },
  {
    id: 'pick-actor',
    target: '[data-tour="table-players"]',
    title: 'Chọn người chơi',
    content: 'Bấm tên người đang ở bàn — người thực hiện hành động.',
    tab: 'players',
    requireAction: true,
    waiting: 'Chọn một người ở bàn.',
  },
  {
    id: 'pick-action',
    target: '[data-tour="action-panel"]',
    title: 'Chọn hành động',
    content: 'Chọn hành động đơn giản (ví dụ: Về nhất, Bị nhốt) để thêm vào danh sách chờ.',
    tab: 'actions',
    requireAction: true,
    waiting: 'Chọn hành động để thêm vào danh sách chờ.',
  },
  {
    id: 'queue-execute',
    target: '[data-tour="queue-execute"]',
    title: 'Hoàn thành danh sách chờ',
    content: 'Bấm Hoàn thành để tính điểm các hành động đã chọn.',
    tab: 'actions',
    requireAction: true,
    waiting: 'Bấm Hoàn thành khi danh sách chờ có hành động.',
  },
  {
    id: 'end-round',
    target: '[data-tour="end-round"]',
    title: 'Kết thúc ván',
    content: 'Kết thúc ván hiện tại và tổng hợp điểm vào phiên.',
    tab: 'scores',
    requireAction: true,
    waiting: 'Bấm Kết thúc ván.',
  },
  {
    id: 'end-session',
    target: '[data-tour="end-session"]',
    title: 'Kết thúc phiên',
    content: 'Đóng phiên chơi và lưu toàn bộ kết quả.',
    requireAction: true,
    waiting: 'Bấm Kết thúc phiên.',
  },
  {
    id: 'open-history',
    target: '[data-tour="history-btn"]',
    title: 'Lịch sử đã chơi',
    content: 'Mở danh sách các phiên và ván đã ghi nhận.',
    requireAction: true,
    waiting: 'Bấm Lịch sử đã chơi.',
  },
  {
    id: 'pick-session',
    target: '[data-tour="history-sessions"]',
    title: 'Chọn phiên vừa chơi',
    content: 'Bấm vào phiên vừa kết thúc để xem chi tiết từng ván.',
    requireAction: true,
    waiting: 'Chọn một phiên trong danh sách.',
  },
  {
    id: 'history-detail',
    target: '[data-tour="history-detail"]',
    title: 'Theo dõi thông tin',
    content: 'Xem điểm từng ván, lịch sử hành động và thống kê đối đầu.',
    waiting: null,
  },
]
