export const TOUR_STORAGE_KEY = 'tienlen_tour_v1_done'

export const TOUR_STEPS = [
  {
    id: 'player-name',
    target: '[data-tour="player-name"]',
    title: 'Nhập tên người chơi',
    content: 'Gõ tên vào ô này — ví dụ: An, Bình, Chi…',
    tab: 'players',
  },
  {
    id: 'player-add',
    target: '[data-tour="player-add"]',
    title: 'Thêm người chơi',
    content: 'Bấm + Thêm để lưu người chơi vào danh sách.',
    tab: 'players',
  },
  {
    id: 'player-select',
    target: '[data-tour="player-select"]',
    fallback: '.panel-left',
    title: 'Chọn người ở bàn',
    content: 'Tick chọn từ 2 đến 4 người sẽ ngồi chơi ván này.',
    tab: 'players',
  },
  {
    id: 'start-session',
    target: '[data-tour="start-session"]',
    fallback: '.header-actions',
    title: 'Bắt đầu phiên',
    content: 'Bấm để mở phiên chơi mới với những người đã chọn.',
    tab: 'players',
  },
  {
    id: 'pick-actor',
    target: '[data-tour="table-players"]',
    fallback: '.panel-left',
    title: 'Chọn người chơi',
    content: 'Bấm tên người đang ở bàn — người thực hiện hành động.',
    tab: 'players',
  },
  {
    id: 'pick-action',
    target: '[data-tour="action-panel"]',
    fallback: '.panel-center',
    title: 'Chọn hành động',
    content: 'Chọn loại hành động: về bài, chặt, phạt…',
    tab: 'actions',
  },
  {
    id: 'queue-execute',
    target: '[data-tour="queue-execute"]',
    fallback: '.panel-center',
    title: 'Hoàn thành danh sách chờ',
    content: 'Bấm Hoàn thành để tính điểm các hành động đã chọn.',
    tab: 'actions',
  },
  {
    id: 'end-round',
    target: '[data-tour="end-round"]',
    fallback: '.header-actions',
    title: 'Kết thúc ván',
    content: 'Kết thúc ván hiện tại và tổng hợp điểm vào phiên.',
    tab: 'scores',
  },
  {
    id: 'end-session',
    target: '[data-tour="end-session"]',
    fallback: '.header-actions',
    title: 'Kết thúc phiên',
    content: 'Đóng phiên chơi và lưu toàn bộ kết quả.',
  },
  {
    id: 'open-history',
    target: '[data-tour="history-btn"]',
    fallback: '.header-actions',
    title: 'Lịch sử đã chơi',
    content: 'Mở danh sách các phiên và ván đã ghi nhận.',
  },
  {
    id: 'pick-session',
    target: '[data-tour="history-sessions"]',
    fallback: '.modal',
    title: 'Chọn phiên vừa chơi',
    content: 'Bấm vào phiên để xem chi tiết từng ván.',
  },
  {
    id: 'history-detail',
    target: '[data-tour="history-detail"]',
    fallback: '.modal',
    title: 'Theo dõi thông tin',
    content: 'Xem điểm từng ván, lịch sử hành động và thống kê đối đầu.',
  },
]
